p8105_hw2_ars2376
================
2025-09-26

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.5.2     ✔ tibble    3.3.0
    ## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
    ## ✔ purrr     1.1.0     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(readxl)
library(dplyr)
```

# Problem 1

Cleaning data from pols-month.csv

``` r
pols_df =
  read_csv("fivethirtyeight_datasets/pols-month.csv", na = c("NA", ".", "")) |> 
  separate(
    mon, into = c("year", "month", "day"), sep = "-") |> 
 mutate(
      month = case_match(
        month, 
        "01" ~ "Jan",
        "02" ~ "Feb",
        "03" ~ "Mar",
        "04" ~ "Apr",
        "05" ~ "May",
        "06" ~ "Jun",
        "07" ~ "Jul",
        "08" ~ "Aug",
        "09" ~ "Sep",
        "10" ~ "Oct",
        "11" ~ "Nov",
        "12" ~"Dec")) |> 
  
  mutate(prez = case_when(
    prez_gop == 1 ~ "gop",
    prez_dem == 1 ~ "dem") 
) |> 
   select(-prez_dem, -prez_gop, -day) 
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
pols_df <- pols_df |> 
  mutate(year = as.numeric(year))
pols_df
```

    ## # A tibble: 822 × 9
    ##     year month gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem prez 
    ##    <dbl> <chr>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>
    ##  1  1947 Jan        23      51     253      23      45     198 dem  
    ##  2  1947 Feb        23      51     253      23      45     198 dem  
    ##  3  1947 Mar        23      51     253      23      45     198 dem  
    ##  4  1947 Apr        23      51     253      23      45     198 dem  
    ##  5  1947 May        23      51     253      23      45     198 dem  
    ##  6  1947 Jun        23      51     253      23      45     198 dem  
    ##  7  1947 Jul        23      51     253      23      45     198 dem  
    ##  8  1947 Aug        23      51     253      23      45     198 dem  
    ##  9  1947 Sep        23      51     253      23      45     198 dem  
    ## 10  1947 Oct        23      51     253      23      45     198 dem  
    ## # ℹ 812 more rows

Clean data from snp.csv

``` r
snp_df =
  read.csv("fivethirtyeight_datasets/snp.csv", na = c("NA", ".", "")) |>
  separate(
    date, into = c("month", "day", "year"), sep = "/") |> 
 mutate(
      month = case_match(
        month, 
        "1" ~ "Jan",
        "2" ~ "Feb",
        "3" ~ "Mar",
        "4" ~ "Apr",
        "5" ~ "May",
        "6" ~ "Jun",
        "7" ~ "Jul",
        "8" ~ "Aug",
        "9" ~ "Sep",
        "10" ~ "Oct",
        "11" ~ "Nov",
        "12" ~"Dec")) |> 
  relocate(year,month) |> 
  select(-day)
```

Change year variable to include 19 or 20

``` r
snp_df <- mutate(snp_df, year = case_when(
  nchar(year) == 2 & as.numeric(year) >= 0 & as.numeric(year) <= 15 ~ paste0("20", year),
  nchar(year) == 1 & as.numeric(year) >= 0 & as.numeric(year) <= 15 ~ paste0("200", year),
  nchar(year) == 2 & as.numeric(year) > 49 ~ paste0("19", year),
  TRUE ~ as.character(year)
))
```

``` r
snp_df
```

    ##     year month   close
    ## 1   2015   Jul 2079.65
    ## 2   2015   Jun 2063.11
    ## 3   2015   May 2107.39
    ## 4   2015   Apr 2085.51
    ## 5   2015   Mar 2067.89
    ## 6   2015   Feb 2104.50
    ## 7   2015   Jan 1994.99
    ## 8   2014   Dec 2058.90
    ## 9   2014   Nov 2067.56
    ## 10  2014   Oct 2018.05
    ## 11  2014   Sep 1972.29
    ## 12  2014   Aug 2003.37
    ## 13  2014   Jul 1930.67
    ## 14  2014   Jun 1960.23
    ## 15  2014   May 1923.57
    ## 16  2014   Apr 1883.95
    ## 17  2014   Mar 1872.34
    ## 18  2014   Feb 1859.45
    ## 19  2014   Jan 1782.59
    ## 20  2013   Dec 1848.36
    ## 21  2013   Nov 1805.81
    ## 22  2013   Oct 1756.54
    ## 23  2013   Sep 1681.55
    ## 24  2013   Aug 1632.97
    ## 25  2013   Jul 1685.73
    ## 26  2013   Jun 1606.28
    ## 27  2013   May 1630.74
    ## 28  2013   Apr 1597.57
    ## 29  2013   Mar 1569.19
    ## 30  2013   Feb 1514.68
    ## 31  2013   Jan 1498.11
    ## 32  2012   Dec 1426.19
    ## 33  2012   Nov 1416.18
    ## 34  2012   Oct 1412.16
    ## 35  2012   Sep 1440.67
    ## 36  2012   Aug 1406.58
    ## 37  2012   Jul 1379.32
    ## 38  2012   Jun 1362.16
    ## 39  2012   May 1310.33
    ## 40  2012   Apr 1397.91
    ## 41  2012   Mar 1408.47
    ## 42  2012   Feb 1365.68
    ## 43  2012   Jan 1312.41
    ## 44  2011   Dec 1257.60
    ## 45  2011   Nov 1246.96
    ## 46  2011   Oct 1253.30
    ## 47  2011   Sep 1131.42
    ## 48  2011   Aug 1218.89
    ## 49  2011   Jul 1292.28
    ## 50  2011   Jun 1320.64
    ## 51  2011   May 1345.20
    ## 52  2011   Apr 1363.61
    ## 53  2011   Mar 1325.83
    ## 54  2011   Feb 1327.22
    ## 55  2011   Jan 1286.12
    ## 56  2010   Dec 1257.64
    ## 57  2010   Nov 1180.55
    ## 58  2010   Oct 1183.26
    ## 59  2010   Sep 1141.20
    ## 60  2010   Aug 1049.33
    ## 61  2010   Jul 1101.60
    ## 62  2010   Jun 1030.71
    ## 63  2010   May 1089.41
    ## 64  2010   Apr 1186.69
    ## 65  2010   Mar 1169.43
    ## 66  2010   Feb 1104.49
    ## 67  2010   Jan 1073.87
    ## 68  2009   Dec 1115.10
    ## 69  2009   Nov 1095.63
    ## 70  2009   Oct 1036.19
    ## 71  2009   Sep 1057.08
    ## 72  2009   Aug 1020.62
    ## 73  2009   Jul  987.48
    ## 74  2009   Jun  919.32
    ## 75  2009   May  919.14
    ## 76  2009   Apr  872.81
    ## 77  2009   Mar  797.87
    ## 78  2009   Feb  735.09
    ## 79  2009   Jan  825.88
    ## 80  2008   Dec  903.25
    ## 81  2008   Nov  896.24
    ## 82  2008   Oct  968.75
    ## 83  2008   Sep 1166.36
    ## 84  2008   Aug 1282.83
    ## 85  2008   Jul 1267.38
    ## 86  2008   Jun 1280.00
    ## 87  2008   May 1400.38
    ## 88  2008   Apr 1385.59
    ## 89  2008   Mar 1322.70
    ## 90  2008   Feb 1330.63
    ## 91  2008   Jan 1378.55
    ## 92  2007   Dec 1468.36
    ## 93  2007   Nov 1481.14
    ## 94  2007   Oct 1549.38
    ## 95  2007   Sep 1526.75
    ## 96  2007   Aug 1473.99
    ## 97  2007   Jul 1455.27
    ## 98  2007   Jun 1503.35
    ## 99  2007   May 1530.62
    ## 100 2007   Apr 1482.37
    ## 101 2007   Mar 1420.86
    ## 102 2007   Feb 1406.82
    ## 103 2007   Jan 1438.24
    ## 104 2006   Dec 1418.30
    ## 105 2006   Nov 1400.63
    ## 106 2006   Oct 1377.94
    ## 107 2006   Sep 1335.85
    ## 108 2006   Aug 1303.82
    ## 109 2006   Jul 1276.66
    ## 110 2006   Jun 1270.20
    ## 111 2006   May 1270.09
    ## 112 2006   Apr 1310.61
    ## 113 2006   Mar 1294.87
    ## 114 2006   Feb 1280.66
    ## 115 2006   Jan 1280.08
    ## 116 2005   Dec 1248.29
    ## 117 2005   Nov 1249.48
    ## 118 2005   Oct 1207.01
    ## 119 2005   Sep 1228.81
    ## 120 2005   Aug 1220.33
    ## 121 2005   Jul 1234.18
    ## 122 2005   Jun 1191.33
    ## 123 2005   May 1191.50
    ## 124 2005   Apr 1156.85
    ## 125 2005   Mar 1180.59
    ## 126 2005   Feb 1203.60
    ## 127 2005   Jan 1181.27
    ## 128 2004   Dec 1211.92
    ## 129 2004   Nov 1173.82
    ## 130 2004   Oct 1130.20
    ## 131 2004   Sep 1114.58
    ## 132 2004   Aug 1104.24
    ## 133 2004   Jul 1101.72
    ## 134 2004   Jun 1140.84
    ## 135 2004   May 1120.68
    ## 136 2004   Apr 1107.30
    ## 137 2004   Mar 1126.21
    ## 138 2004   Feb 1144.94
    ## 139 2004   Jan 1131.13
    ## 140 2003   Dec 1111.92
    ## 141 2003   Nov 1058.20
    ## 142 2003   Oct 1050.71
    ## 143 2003   Sep  995.97
    ## 144 2003   Aug 1008.01
    ## 145 2003   Jul  990.31
    ## 146 2003   Jun  974.50
    ## 147 2003   May  963.59
    ## 148 2003   Apr  916.92
    ## 149 2003   Mar  848.18
    ## 150 2003   Feb  841.15
    ## 151 2003   Jan  855.70
    ## 152 2002   Dec  879.82
    ## 153 2002   Nov  936.31
    ## 154 2002   Oct  885.76
    ## 155 2002   Sep  815.28
    ## 156 2002   Aug  916.07
    ## 157 2002   Jul  911.62
    ## 158 2002   Jun  989.82
    ## 159 2002   May 1067.14
    ## 160 2002   Apr 1076.92
    ## 161 2002   Mar 1147.39
    ## 162 2002   Feb 1106.73
    ## 163 2002   Jan 1130.20
    ## 164 2001   Dec 1148.08
    ## 165 2001   Nov 1139.45
    ## 166 2001   Oct 1059.78
    ## 167 2001   Sep 1040.94
    ## 168 2001   Aug 1133.58
    ## 169 2001   Jul 1211.23
    ## 170 2001   Jun 1224.38
    ## 171 2001   May 1255.82
    ## 172 2001   Apr 1249.46
    ## 173 2001   Mar 1160.33
    ## 174 2001   Feb 1239.94
    ## 175 2001   Jan 1366.01
    ## 176 2000   Dec 1320.28
    ## 177 2000   Nov 1314.95
    ## 178 2000   Oct 1429.40
    ## 179 2000   Sep 1436.51
    ## 180 2000   Aug 1517.68
    ## 181 2000   Jul 1430.83
    ## 182 2000   Jun 1454.60
    ## 183 2000   May 1420.60
    ## 184 2000   Apr 1452.43
    ## 185 2000   Mar 1498.58
    ## 186 2000   Feb 1366.42
    ## 187 2000   Jan 1394.46
    ## 188 1999   Dec 1469.25
    ## 189 1999   Nov 1388.91
    ## 190 1999   Oct 1362.93
    ## 191 1999   Sep 1282.71
    ## 192 1999   Aug 1320.41
    ## 193 1999   Jul 1328.72
    ## 194 1999   Jun 1372.71
    ## 195 1999   May 1301.84
    ## 196 1999   Apr 1335.18
    ## 197 1999   Mar 1286.37
    ## 198 1999   Feb 1238.33
    ## 199 1999   Jan 1279.64
    ## 200 1998   Dec 1229.23
    ## 201 1998   Nov 1163.63
    ## 202 1998   Oct 1098.67
    ## 203 1998   Sep 1017.01
    ## 204 1998   Aug  957.28
    ## 205 1998   Jul 1120.67
    ## 206 1998   Jun 1133.84
    ## 207 1998   May 1090.82
    ## 208 1998   Apr 1111.75
    ## 209 1998   Mar 1101.75
    ## 210 1998   Feb 1049.34
    ## 211 1998   Jan  980.28
    ## 212 1997   Dec  970.43
    ## 213 1997   Nov  955.40
    ## 214 1997   Oct  914.62
    ## 215 1997   Sep  947.28
    ## 216 1997   Aug  899.47
    ## 217 1997   Jul  954.31
    ## 218 1997   Jun  885.14
    ## 219 1997   May  848.28
    ## 220 1997   Apr  801.34
    ## 221 1997   Mar  757.12
    ## 222 1997   Feb  790.82
    ## 223 1997   Jan  786.16
    ## 224 1996   Dec  740.74
    ## 225 1996   Nov  757.02
    ## 226 1996   Oct  705.27
    ## 227 1996   Sep  687.33
    ## 228 1996   Aug  651.99
    ## 229 1996   Jul  639.95
    ## 230 1996   Jun  670.63
    ## 231 1996   May  669.12
    ## 232 1996   Apr  654.17
    ## 233 1996   Mar  645.50
    ## 234 1996   Feb  640.43
    ## 235 1996   Jan  636.02
    ## 236 1995   Dec  615.93
    ## 237 1995   Nov  605.37
    ## 238 1995   Oct  581.50
    ## 239 1995   Sep  584.41
    ## 240 1995   Aug  561.88
    ## 241 1995   Jul  562.06
    ## 242 1995   Jun  544.75
    ## 243 1995   May  533.40
    ## 244 1995   Apr  514.71
    ## 245 1995   Mar  500.71
    ## 246 1995   Feb  487.39
    ## 247 1995   Jan  470.42
    ## 248 1994   Dec  459.27
    ## 249 1994   Nov  453.69
    ## 250 1994   Oct  472.35
    ## 251 1994   Sep  462.71
    ## 252 1994   Aug  475.49
    ## 253 1994   Jul  458.26
    ## 254 1994   Jun  444.27
    ## 255 1994   May  456.50
    ## 256 1994   Apr  450.91
    ## 257 1994   Mar  445.77
    ## 258 1994   Feb  467.14
    ## 259 1994   Jan  481.61
    ## 260 1993   Dec  466.45
    ## 261 1993   Nov  461.79
    ## 262 1993   Oct  467.83
    ## 263 1993   Sep  458.93
    ## 264 1993   Aug  463.56
    ## 265 1993   Jul  448.13
    ## 266 1993   Jun  450.53
    ## 267 1993   May  450.19
    ## 268 1993   Apr  440.19
    ## 269 1993   Mar  451.67
    ## 270 1993   Feb  443.38
    ## 271 1993   Jan  438.78
    ## 272 1992   Dec  435.71
    ## 273 1992   Nov  431.35
    ## 274 1992   Oct  418.68
    ## 275 1992   Sep  417.80
    ## 276 1992   Aug  414.03
    ## 277 1992   Jul  424.21
    ## 278 1992   Jun  408.14
    ## 279 1992   May  415.35
    ## 280 1992   Apr  414.95
    ## 281 1992   Mar  403.69
    ## 282 1992   Feb  412.70
    ## 283 1992   Jan  408.78
    ## 284 1991   Dec  417.09
    ## 285 1991   Nov  375.22
    ## 286 1991   Oct  392.45
    ## 287 1991   Sep  387.86
    ## 288 1991   Aug  395.43
    ## 289 1991   Jul  387.81
    ## 290 1991   Jun  371.16
    ## 291 1991   May  389.83
    ## 292 1991   Apr  375.34
    ## 293 1991   Mar  375.22
    ## 294 1991   Feb  367.07
    ## 295 1991   Jan  343.93
    ## 296 1990   Dec  330.22
    ## 297 1990   Nov  322.22
    ## 298 1990   Oct  304.00
    ## 299 1990   Sep  306.05
    ## 300 1990   Aug  322.56
    ## 301 1990   Jul  356.15
    ## 302 1990   Jun  358.02
    ## 303 1990   May  361.23
    ## 304 1990   Apr  330.80
    ## 305 1990   Mar  339.94
    ## 306 1990   Feb  331.89
    ## 307 1990   Jan  329.08
    ## 308 1989   Dec  353.40
    ## 309 1989   Nov  345.99
    ## 310 1989   Oct  340.36
    ## 311 1989   Sep  349.15
    ## 312 1989   Aug  351.45
    ## 313 1989   Jul  346.08
    ## 314 1989   Jun  317.98
    ## 315 1989   May  320.52
    ## 316 1989   Apr  309.64
    ## 317 1989   Mar  294.87
    ## 318 1989   Feb  288.86
    ## 319 1989   Jan  297.47
    ## 320 1988   Dec  277.72
    ## 321 1988   Nov  273.70
    ## 322 1988   Oct  278.97
    ## 323 1988   Sep  271.91
    ## 324 1988   Aug  261.52
    ## 325 1988   Jul  272.02
    ## 326 1988   Jun  273.50
    ## 327 1988   May  262.16
    ## 328 1988   Apr  261.33
    ## 329 1988   Mar  258.89
    ## 330 1988   Feb  267.82
    ## 331 1988   Jan  257.07
    ## 332 1987   Dec  247.08
    ## 333 1987   Nov  230.30
    ## 334 1987   Oct  251.79
    ## 335 1987   Sep  321.83
    ## 336 1987   Aug  329.80
    ## 337 1987   Jul  318.66
    ## 338 1987   Jun  304.00
    ## 339 1987   May  290.10
    ## 340 1987   Apr  288.36
    ## 341 1987   Mar  291.70
    ## 342 1987   Feb  284.20
    ## 343 1987   Jan  274.08
    ## 344 1986   Dec  242.17
    ## 345 1986   Nov  249.22
    ## 346 1986   Oct  243.98
    ## 347 1986   Sep  231.32
    ## 348 1986   Aug  252.93
    ## 349 1986   Jul  236.12
    ## 350 1986   Jun  250.84
    ## 351 1986   May  247.35
    ## 352 1986   Apr  235.52
    ## 353 1986   Mar  238.90
    ## 354 1986   Feb  226.92
    ## 355 1986   Jan  211.78
    ## 356 1985   Dec  211.28
    ## 357 1985   Nov  202.17
    ## 358 1985   Oct  189.82
    ## 359 1985   Sep  182.08
    ## 360 1985   Aug  188.63
    ## 361 1985   Jul  190.92
    ## 362 1985   Jun  191.85
    ## 363 1985   May  189.55
    ## 364 1985   Apr  179.83
    ## 365 1985   Mar  180.66
    ## 366 1985   Feb  181.18
    ## 367 1985   Jan  179.63
    ## 368 1984   Dec  167.24
    ## 369 1984   Nov  163.58
    ## 370 1984   Oct  166.09
    ## 371 1984   Sep  166.10
    ## 372 1984   Aug  166.68
    ## 373 1984   Jul  150.66
    ## 374 1984   Jun  153.18
    ## 375 1984   May  150.55
    ## 376 1984   Apr  160.05
    ## 377 1984   Mar  159.18
    ## 378 1984   Feb  157.06
    ## 379 1984   Jan  163.41
    ## 380 1983   Dec  164.93
    ## 381 1983   Nov  166.40
    ## 382 1983   Oct  163.55
    ## 383 1983   Sep  166.07
    ## 384 1983   Aug  164.40
    ## 385 1983   Jul  162.56
    ## 386 1983   Jun  167.64
    ## 387 1983   May  162.39
    ## 388 1983   Apr  164.43
    ## 389 1983   Mar  152.96
    ## 390 1983   Feb  148.06
    ## 391 1983   Jan  145.30
    ## 392 1982   Dec  140.64
    ## 393 1982   Nov  138.53
    ## 394 1982   Oct  133.72
    ## 395 1982   Sep  120.42
    ## 396 1982   Aug  119.51
    ## 397 1982   Jul  107.09
    ## 398 1982   Jun  109.61
    ## 399 1982   May  111.88
    ## 400 1982   Apr  116.44
    ## 401 1982   Mar  111.96
    ## 402 1982   Feb  113.11
    ## 403 1982   Jan  120.40
    ## 404 1981   Dec  122.55
    ## 405 1981   Nov  126.35
    ## 406 1981   Oct  121.89
    ## 407 1981   Sep  116.18
    ## 408 1981   Aug  122.79
    ## 409 1981   Jul  130.92
    ## 410 1981   Jun  131.21
    ## 411 1981   May  132.59
    ## 412 1981   Apr  132.81
    ## 413 1981   Mar  136.00
    ## 414 1981   Feb  131.27
    ## 415 1981   Jan  129.55
    ## 416 1980   Dec  135.76
    ## 417 1980   Nov  140.52
    ## 418 1980   Oct  127.47
    ## 419 1980   Sep  125.46
    ## 420 1980   Aug  122.38
    ## 421 1980   Jul  121.67
    ## 422 1980   Jun  114.24
    ## 423 1980   May  111.24
    ## 424 1980   Apr  106.29
    ## 425 1980   Mar  102.09
    ## 426 1980   Feb  113.66
    ## 427 1980   Jan  114.16
    ## 428 1979   Dec  107.94
    ## 429 1979   Nov  106.16
    ## 430 1979   Oct  101.82
    ## 431 1979   Sep  109.32
    ## 432 1979   Aug  109.32
    ## 433 1979   Jul  103.81
    ## 434 1979   Jun  102.91
    ## 435 1979   May   99.08
    ## 436 1979   Apr  101.76
    ## 437 1979   Mar  101.59
    ## 438 1979   Feb   96.28
    ## 439 1979   Jan   99.93
    ## 440 1978   Dec   96.11
    ## 441 1978   Nov   94.70
    ## 442 1978   Oct   93.15
    ## 443 1978   Sep  102.54
    ## 444 1978   Aug  103.29
    ## 445 1978   Jul  100.68
    ## 446 1978   Jun   95.53
    ## 447 1978   May   97.24
    ## 448 1978   Apr   96.83
    ## 449 1978   Mar   89.21
    ## 450 1978   Feb   87.04
    ## 451 1978   Jan   89.25
    ## 452 1977   Dec   95.10
    ## 453 1977   Nov   94.83
    ## 454 1977   Oct   92.34
    ## 455 1977   Sep   96.53
    ## 456 1977   Aug   96.77
    ## 457 1977   Jul   98.85
    ## 458 1977   Jun  100.48
    ## 459 1977   May   96.12
    ## 460 1977   Apr   98.44
    ## 461 1977   Mar   98.42
    ## 462 1977   Feb   99.82
    ## 463 1977   Jan  102.03
    ## 464 1976   Dec  107.46
    ## 465 1976   Nov  102.10
    ## 466 1976   Oct  102.90
    ## 467 1976   Sep  105.24
    ## 468 1976   Aug  102.91
    ## 469 1976   Jul  103.44
    ## 470 1976   Jun  104.28
    ## 471 1976   May  100.18
    ## 472 1976   Apr  101.64
    ## 473 1976   Mar  102.77
    ## 474 1976   Feb   99.71
    ## 475 1976   Jan  100.86
    ## 476 1975   Dec   90.19
    ## 477 1975   Nov   91.24
    ## 478 1975   Oct   89.04
    ## 479 1975   Sep   83.87
    ## 480 1975   Aug   86.88
    ## 481 1975   Jul   88.75
    ## 482 1975   Jun   95.19
    ## 483 1975   May   91.15
    ## 484 1975   Apr   87.30
    ## 485 1975   Mar   83.36
    ## 486 1975   Feb   81.59
    ## 487 1975   Jan   76.98
    ## 488 1974   Dec   68.56
    ## 489 1974   Nov   69.97
    ## 490 1974   Oct   73.90
    ## 491 1974   Sep   63.54
    ## 492 1974   Aug   72.15
    ## 493 1974   Jul   79.31
    ## 494 1974   Jun   86.00
    ## 495 1974   May   87.28
    ## 496 1974   Apr   90.31
    ## 497 1974   Mar   93.98
    ## 498 1974   Feb   96.22
    ## 499 1974   Jan   96.57
    ## 500 1973   Dec   97.55
    ## 501 1973   Nov   95.96
    ## 502 1973   Oct  108.29
    ## 503 1973   Sep  108.43
    ## 504 1973   Aug  104.25
    ## 505 1973   Jul  108.22
    ## 506 1973   Jun  104.26
    ## 507 1973   May  104.95
    ## 508 1973   Apr  106.97
    ## 509 1973   Mar  111.52
    ## 510 1973   Feb  111.68
    ## 511 1973   Jan  116.03
    ## 512 1972   Dec  118.05
    ## 513 1972   Nov  116.67
    ## 514 1972   Oct  111.58
    ## 515 1972   Sep  110.55
    ## 516 1972   Aug  111.09
    ## 517 1972   Jul  107.39
    ## 518 1972   Jun  107.14
    ## 519 1972   May  109.53
    ## 520 1972   Apr  107.67
    ## 521 1972   Mar  107.20
    ## 522 1972   Feb  106.57
    ## 523 1972   Jan  103.94
    ## 524 1971   Dec  102.09
    ## 525 1971   Nov   93.99
    ## 526 1971   Oct   94.23
    ## 527 1971   Sep   98.34
    ## 528 1971   Aug   99.03
    ## 529 1971   Jul   95.58
    ## 530 1971   Jun   98.70
    ## 531 1971   May   99.63
    ## 532 1971   Apr  103.95
    ## 533 1971   Mar  100.31
    ## 534 1971   Feb   96.75
    ## 535 1971   Jan   95.88
    ## 536 1970   Dec   92.15
    ## 537 1970   Nov   87.20
    ## 538 1970   Oct   83.25
    ## 539 1970   Sep   84.30
    ## 540 1970   Aug   81.52
    ## 541 1970   Jul   78.05
    ## 542 1970   Jun   72.72
    ## 543 1970   May   76.55
    ## 544 1970   Apr   81.52
    ## 545 1970   Mar   89.63
    ## 546 1970   Feb   89.50
    ## 547 1970   Jan   85.02
    ## 548 1969   Dec   92.06
    ## 549 1969   Nov   93.81
    ## 550 1969   Oct   97.12
    ## 551 1969   Sep   93.12
    ## 552 1969   Aug   95.51
    ## 553 1969   Jul   91.83
    ## 554 1969   Jun   97.71
    ## 555 1969   May  103.46
    ## 556 1969   Apr  103.69
    ## 557 1969   Mar  101.51
    ## 558 1969   Feb   98.13
    ## 559 1969   Jan  103.01
    ## 560 1968   Dec  103.86
    ## 561 1968   Nov  108.37
    ## 562 1968   Oct  103.41
    ## 563 1968   Sep  102.67
    ## 564 1968   Aug   98.86
    ## 565 1968   Jul   97.74
    ## 566 1968   Jun   99.58
    ## 567 1968   May   98.68
    ## 568 1968   Apr   97.46
    ## 569 1968   Mar   90.20
    ## 570 1968   Feb   89.36
    ## 571 1968   Jan   92.24
    ## 572 1967   Dec   96.47
    ## 573 1967   Nov   94.00
    ## 574 1967   Oct   93.30
    ## 575 1967   Sep   96.71
    ## 576 1967   Aug   93.64
    ## 577 1967   Jul   94.75
    ## 578 1967   Jun   90.64
    ## 579 1967   May   89.08
    ## 580 1967   Apr   94.01
    ## 581 1967   Mar   90.20
    ## 582 1967   Feb   86.78
    ## 583 1967   Jan   86.61
    ## 584 1966   Dec   80.33
    ## 585 1966   Nov   80.45
    ## 586 1966   Oct   80.20
    ## 587 1966   Sep   76.56
    ## 588 1966   Aug   77.10
    ## 589 1966   Jul   83.60
    ## 590 1966   Jun   84.74
    ## 591 1966   May   86.13
    ## 592 1966   Apr   91.06
    ## 593 1966   Mar   89.23
    ## 594 1966   Feb   91.22
    ## 595 1966   Jan   92.88
    ## 596 1965   Dec   92.43
    ## 597 1965   Nov   91.61
    ## 598 1965   Oct   92.42
    ## 599 1965   Sep   89.96
    ## 600 1965   Aug   87.17
    ## 601 1965   Jul   85.25
    ## 602 1965   Jun   84.12
    ## 603 1965   May   88.42
    ## 604 1965   Apr   89.11
    ## 605 1965   Mar   86.16
    ## 606 1965   Feb   87.43
    ## 607 1965   Jan   87.56
    ## 608 1964   Dec   84.75
    ## 609 1964   Nov   84.42
    ## 610 1964   Oct   84.86
    ## 611 1964   Sep   84.18
    ## 612 1964   Aug   81.83
    ## 613 1964   Jul   83.18
    ## 614 1964   Jun   81.69
    ## 615 1964   May   80.37
    ## 616 1964   Apr   79.46
    ## 617 1964   Mar   78.98
    ## 618 1964   Feb   77.80
    ## 619 1964   Jan   77.04
    ## 620 1963   Dec   75.02
    ## 621 1963   Nov   73.23
    ## 622 1963   Oct   74.01
    ## 623 1963   Sep   71.70
    ## 624 1963   Aug   72.50
    ## 625 1963   Jul   69.13
    ## 626 1963   Jun   69.37
    ## 627 1963   May   70.80
    ## 628 1963   Apr   69.80
    ## 629 1963   Mar   66.57
    ## 630 1963   Feb   64.29
    ## 631 1963   Jan   66.20
    ## 632 1962   Dec   63.10
    ## 633 1962   Nov   62.26
    ## 634 1962   Oct   56.52
    ## 635 1962   Sep   56.27
    ## 636 1962   Aug   59.12
    ## 637 1962   Jul   58.23
    ## 638 1962   Jun   54.75
    ## 639 1962   May   59.63
    ## 640 1962   Apr   65.24
    ## 641 1962   Mar   69.55
    ## 642 1962   Feb   69.96
    ## 643 1962   Jan   68.84
    ## 644 1961   Dec   71.55
    ## 645 1961   Nov   71.32
    ## 646 1961   Oct   68.62
    ## 647 1961   Sep   66.73
    ## 648 1961   Aug   68.07
    ## 649 1961   Jul   66.76
    ## 650 1961   Jun   64.64
    ## 651 1961   May   66.56
    ## 652 1961   Apr   65.31
    ## 653 1961   Mar   65.06
    ## 654 1961   Feb   63.44
    ## 655 1961   Jan   61.78
    ## 656 1960   Dec   58.11
    ## 657 1960   Nov   55.54
    ## 658 1960   Oct   53.39
    ## 659 1960   Sep   53.52
    ## 660 1960   Aug   56.96
    ## 661 1960   Jul   55.51
    ## 662 1960   Jun   56.92
    ## 663 1960   May   55.83
    ## 664 1960   Apr   54.37
    ## 665 1960   Mar   55.34
    ## 666 1960   Feb   56.12
    ## 667 1960   Jan   55.61
    ## 668 1959   Dec   59.89
    ## 669 1959   Nov   58.28
    ## 670 1959   Oct   57.52
    ## 671 1959   Sep   56.88
    ## 672 1959   Aug   59.60
    ## 673 1959   Jul   60.51
    ## 674 1959   Jun   58.47
    ## 675 1959   May   58.68
    ## 676 1959   Apr   57.59
    ## 677 1959   Mar   55.44
    ## 678 1959   Feb   55.41
    ## 679 1959   Jan   55.45
    ## 680 1958   Dec   55.21
    ## 681 1958   Nov   52.48
    ## 682 1958   Oct   51.33
    ## 683 1958   Sep   50.06
    ## 684 1958   Aug   47.75
    ## 685 1958   Jul   47.19
    ## 686 1958   Jun   45.24
    ## 687 1958   May   44.09
    ## 688 1958   Apr   43.44
    ## 689 1958   Mar   42.10
    ## 690 1958   Feb   40.84
    ## 691 1958   Jan   41.70
    ## 692 1957   Dec   39.99
    ## 693 1957   Nov   41.72
    ## 694 1957   Oct   41.06
    ## 695 1957   Sep   42.42
    ## 696 1957   Aug   45.22
    ## 697 1957   Jul   47.91
    ## 698 1957   Jun   47.37
    ## 699 1957   May   47.43
    ## 700 1957   Apr   45.74
    ## 701 1957   Mar   44.11
    ## 702 1957   Feb   43.26
    ## 703 1957   Jan   44.72
    ## 704 1956   Dec   46.67
    ## 705 1956   Nov   45.08
    ## 706 1956   Oct   45.58
    ## 707 1956   Sep   45.35
    ## 708 1956   Aug   47.51
    ## 709 1956   Jul   49.39
    ## 710 1956   Jun   46.97
    ## 711 1956   May   45.20
    ## 712 1956   Apr   48.38
    ## 713 1956   Mar   48.48
    ## 714 1956   Feb   45.34
    ## 715 1956   Jan   43.82
    ## 716 1955   Dec   45.48
    ## 717 1955   Nov   45.51
    ## 718 1955   Oct   42.34
    ## 719 1955   Sep   43.67
    ## 720 1955   Aug   43.18
    ## 721 1955   Jul   43.52
    ## 722 1955   Jun   41.03
    ## 723 1955   May   37.91
    ## 724 1955   Apr   37.96
    ## 725 1955   Mar   36.58
    ## 726 1955   Feb   36.76
    ## 727 1955   Jan   36.63
    ## 728 1954   Dec   35.98
    ## 729 1954   Nov   34.24
    ## 730 1954   Oct   31.68
    ## 731 1954   Sep   32.31
    ## 732 1954   Aug   29.83
    ## 733 1954   Jul   30.88
    ## 734 1954   Jun   29.21
    ## 735 1954   May   29.19
    ## 736 1954   Apr   28.26
    ## 737 1954   Mar   26.94
    ## 738 1954   Feb   26.15
    ## 739 1954   Jan   26.08
    ## 740 1953   Dec   24.81
    ## 741 1953   Nov   24.76
    ## 742 1953   Oct   24.54
    ## 743 1953   Sep   23.35
    ## 744 1953   Aug   23.32
    ## 745 1953   Jul   24.75
    ## 746 1953   Jun   24.14
    ## 747 1953   May   24.54
    ## 748 1953   Apr   24.62
    ## 749 1953   Mar   25.29
    ## 750 1953   Feb   25.90
    ## 751 1953   Jan   26.38
    ## 752 1952   Dec   26.57
    ## 753 1952   Nov   25.66
    ## 754 1952   Oct   24.52
    ## 755 1952   Sep   24.54
    ## 756 1952   Aug   25.03
    ## 757 1952   Jul   25.40
    ## 758 1952   Jun   24.96
    ## 759 1952   May   23.86
    ## 760 1952   Apr   23.32
    ## 761 1952   Mar   24.37
    ## 762 1952   Feb   23.26
    ## 763 1952   Jan   24.14
    ## 764 1951   Dec   23.77
    ## 765 1951   Nov   22.88
    ## 766 1951   Oct   22.94
    ## 767 1951   Sep   23.26
    ## 768 1951   Aug   23.28
    ## 769 1951   Jul   22.40
    ## 770 1951   Jun   20.96
    ## 771 1951   May   21.52
    ## 772 1951   Apr   22.43
    ## 773 1951   Mar   21.48
    ## 774 1951   Feb   21.80
    ## 775 1951   Jan   21.66
    ## 776 1950   Dec   20.43
    ## 777 1950   Nov   19.51
    ## 778 1950   Oct   19.53
    ## 779 1950   Sep   19.45
    ## 780 1950   Aug   18.42
    ## 781 1950   Jul   17.84
    ## 782 1950   Jun   17.69
    ## 783 1950   May   18.78
    ## 784 1950   Apr   17.96
    ## 785 1950   Mar   17.29
    ## 786 1950   Feb   17.22
    ## 787 1950   Jan   17.05

Tidy unemployment.csv for merging

``` r
unemp_df =
  read.csv("fivethirtyeight_datasets/unemployment.csv", na = c("NA", ".", "")) |> 
  pivot_longer(
    cols = Jan:Dec,
    names_to = "month",
    values_to = "unemp_pct"
  ) |> 
  janitor::clean_names() ## Changed Year to year
```

``` r
unemp_df <- unemp_df |> 
  mutate(year = as.numeric(year))

unemp_df
```

    ## # A tibble: 816 × 3
    ##     year month unemp_pct
    ##    <dbl> <chr>     <dbl>
    ##  1  1948 Jan         3.4
    ##  2  1948 Feb         3.8
    ##  3  1948 Mar         4  
    ##  4  1948 Apr         3.9
    ##  5  1948 May         3.5
    ##  6  1948 Jun         3.6
    ##  7  1948 Jul         3.6
    ##  8  1948 Aug         3.9
    ##  9  1948 Sep         3.8
    ## 10  1948 Oct         3.7
    ## # ℹ 806 more rows

Merge snp into pols

``` r
pols_df <- pols_df |> 
  mutate(year = as.numeric(year))

snp_df <- snp_df |> 
  mutate(year = as.numeric(year))

pols_snp_df = 
  left_join(pols_df, snp_df, by = c("year","month"))
```

``` r
pols_snp_df
```

    ## # A tibble: 822 × 10
    ##     year month gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem prez  close
    ##    <dbl> <chr>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr> <dbl>
    ##  1  1947 Jan        23      51     253      23      45     198 dem      NA
    ##  2  1947 Feb        23      51     253      23      45     198 dem      NA
    ##  3  1947 Mar        23      51     253      23      45     198 dem      NA
    ##  4  1947 Apr        23      51     253      23      45     198 dem      NA
    ##  5  1947 May        23      51     253      23      45     198 dem      NA
    ##  6  1947 Jun        23      51     253      23      45     198 dem      NA
    ##  7  1947 Jul        23      51     253      23      45     198 dem      NA
    ##  8  1947 Aug        23      51     253      23      45     198 dem      NA
    ##  9  1947 Sep        23      51     253      23      45     198 dem      NA
    ## 10  1947 Oct        23      51     253      23      45     198 dem      NA
    ## # ℹ 812 more rows

Merge unemp into pols_snp

``` r
final_df =
  left_join(pols_snp_df, unemp_df, by = c("year", "month"))
```

``` r
final_df
```

    ## # A tibble: 822 × 11
    ##     year month gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem prez  close
    ##    <dbl> <chr>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr> <dbl>
    ##  1  1947 Jan        23      51     253      23      45     198 dem      NA
    ##  2  1947 Feb        23      51     253      23      45     198 dem      NA
    ##  3  1947 Mar        23      51     253      23      45     198 dem      NA
    ##  4  1947 Apr        23      51     253      23      45     198 dem      NA
    ##  5  1947 May        23      51     253      23      45     198 dem      NA
    ##  6  1947 Jun        23      51     253      23      45     198 dem      NA
    ##  7  1947 Jul        23      51     253      23      45     198 dem      NA
    ##  8  1947 Aug        23      51     253      23      45     198 dem      NA
    ##  9  1947 Sep        23      51     253      23      45     198 dem      NA
    ## 10  1947 Oct        23      51     253      23      45     198 dem      NA
    ## # ℹ 812 more rows
    ## # ℹ 1 more variable: unemp_pct <dbl>

### Write-up

One of the datasets used is the `pols-month` dataset, which describes
the number of national politicians who are Democratic or Republican at
any given time. Some key variables include date of the count, whether
the president was Democratic or Republic on the associated date, number
of Republican governors, number of Republican senators, number of
Republican representatives, number of Democratic governors, number of
Democratic senators, and number of Democratic representatives. The `snp`
dataset describes the closing values of the Standard & Poor stock market
index for a set of dates. The `unemployment` dataset measures the
percentage of unemployment. The merged dataset of all 3 `final_df`
contains 822 observations of 12 variables and the date ranges from 1947
to 2015.

## Problem 2

Clean data for Mr. Trash Wheel

``` r
trashwh_df =
  read_excel("202509 Trash Wheel Collection Data.xlsx", sheet = "Mr. Trash Wheel", na = c("NA", ".", ""), skip = 1, col_names = TRUE) |>
  janitor::clean_names() |> 
  head(707) |>  ## Omits last row
  mutate(sports_balls = as.integer(round(sports_balls))) |> 
  mutate(year = as.numeric(year)) |> 
  mutate(name = "Mr. Trash Wheel") |> 
  relocate(name)
```

``` r
trashwh_df
```

    ## # A tibble: 707 × 15
    ##    name  dumpster month  year date                weight_tons volume_cubic_yards
    ##    <chr>    <dbl> <chr> <dbl> <dttm>                    <dbl>              <dbl>
    ##  1 Mr. …        1 May    2014 2014-05-16 00:00:00        4.31                 18
    ##  2 Mr. …        2 May    2014 2014-05-16 00:00:00        2.74                 13
    ##  3 Mr. …        3 May    2014 2014-05-16 00:00:00        3.45                 15
    ##  4 Mr. …        4 May    2014 2014-05-17 00:00:00        3.1                  15
    ##  5 Mr. …        5 May    2014 2014-05-17 00:00:00        4.06                 18
    ##  6 Mr. …        6 May    2014 2014-05-20 00:00:00        2.71                 13
    ##  7 Mr. …        7 May    2014 2014-05-21 00:00:00        1.91                  8
    ##  8 Mr. …        8 May    2014 2014-05-28 00:00:00        3.7                  16
    ##  9 Mr. …        9 June   2014 2014-06-05 00:00:00        2.52                 14
    ## 10 Mr. …       10 June   2014 2014-06-11 00:00:00        3.76                 18
    ## # ℹ 697 more rows
    ## # ℹ 8 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <int>, homes_powered <dbl>

Clean data for Professor Trash Wheel

``` r
proftrashwh_df =
  read_excel("202509 Trash Wheel Collection Data.xlsx", sheet = "Professor Trash Wheel", na = c("NA", ".", ""), skip = 1, col_names = TRUE) |>
  janitor::clean_names() |> 
  head(132) |> ## Omits last row
  mutate(name = "Professor Trash Wheel") |> 
  relocate(name)
```

``` r
proftrashwh_df
```

    ## # A tibble: 132 × 14
    ##    name  dumpster month  year date                weight_tons volume_cubic_yards
    ##    <chr>    <dbl> <chr> <dbl> <dttm>                    <dbl>              <dbl>
    ##  1 Prof…        1 Janu…  2017 2017-01-02 00:00:00        1.79                 15
    ##  2 Prof…        2 Janu…  2017 2017-01-30 00:00:00        1.58                 15
    ##  3 Prof…        3 Febr…  2017 2017-02-26 00:00:00        2.32                 18
    ##  4 Prof…        4 Febr…  2017 2017-02-26 00:00:00        3.72                 15
    ##  5 Prof…        5 Febr…  2017 2017-02-28 00:00:00        1.45                 15
    ##  6 Prof…        6 March  2017 2017-03-30 00:00:00        1.71                 15
    ##  7 Prof…        7 April  2017 2017-04-01 00:00:00        1.82                 15
    ##  8 Prof…        8 April  2017 2017-04-20 00:00:00        2.37                 15
    ##  9 Prof…        9 May    2017 2017-05-10 00:00:00        2.64                 15
    ## 10 Prof…       10 May    2017 2017-05-26 00:00:00        2.78                 15
    ## # ℹ 122 more rows
    ## # ℹ 7 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, homes_powered <dbl>

Clean data for Gwynnda

``` r
gwynnda_df =
  read_excel("202509 Trash Wheel Collection Data.xlsx", sheet = "Gwynnda Falls Trash Wheel", na = c("NA", ".", ""), skip = 1, col_names = TRUE) |>
  janitor::clean_names() |> 
  head(349) |>  ## Omits last row
  mutate(name = "Gwynnda Trash Wheel") |> 
  relocate(name)
```

``` r
gwynnda_df
```

    ## # A tibble: 349 × 13
    ##    name  dumpster month  year date                weight_tons volume_cubic_yards
    ##    <chr>    <dbl> <chr> <dbl> <dttm>                    <dbl>              <dbl>
    ##  1 Gwyn…        1 July   2021 2021-07-03 00:00:00        0.93                 15
    ##  2 Gwyn…        2 July   2021 2021-07-07 00:00:00        2.26                 15
    ##  3 Gwyn…        3 July   2021 2021-07-07 00:00:00        1.62                 15
    ##  4 Gwyn…        4 July   2021 2021-07-16 00:00:00        1.76                 15
    ##  5 Gwyn…        5 July   2021 2021-07-30 00:00:00        1.53                 15
    ##  6 Gwyn…        6 Augu…  2021 2021-08-11 00:00:00        2.06                 15
    ##  7 Gwyn…        7 Augu…  2021 2021-08-14 00:00:00        1.9                  15
    ##  8 Gwyn…        8 Augu…  2021 2021-08-16 00:00:00        2.16                 15
    ##  9 Gwyn…        9 Augu…  2021 2021-08-16 00:00:00        2.6                  15
    ## 10 Gwyn…       10 Augu…  2021 2021-08-17 00:00:00        3.21                 15
    ## # ℹ 339 more rows
    ## # ℹ 6 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, plastic_bags <dbl>, wrappers <dbl>,
    ## #   homes_powered <dbl>

Merge datasets

``` r
alltrash_df = 
  bind_rows(trashwh_df, proftrashwh_df, gwynnda_df)
```

``` r
alltrash_df
```

    ## # A tibble: 1,188 × 15
    ##    name  dumpster month  year date                weight_tons volume_cubic_yards
    ##    <chr>    <dbl> <chr> <dbl> <dttm>                    <dbl>              <dbl>
    ##  1 Mr. …        1 May    2014 2014-05-16 00:00:00        4.31                 18
    ##  2 Mr. …        2 May    2014 2014-05-16 00:00:00        2.74                 13
    ##  3 Mr. …        3 May    2014 2014-05-16 00:00:00        3.45                 15
    ##  4 Mr. …        4 May    2014 2014-05-17 00:00:00        3.1                  15
    ##  5 Mr. …        5 May    2014 2014-05-17 00:00:00        4.06                 18
    ##  6 Mr. …        6 May    2014 2014-05-20 00:00:00        2.71                 13
    ##  7 Mr. …        7 May    2014 2014-05-21 00:00:00        1.91                  8
    ##  8 Mr. …        8 May    2014 2014-05-28 00:00:00        3.7                  16
    ##  9 Mr. …        9 June   2014 2014-06-05 00:00:00        2.52                 14
    ## 10 Mr. …       10 June   2014 2014-06-11 00:00:00        3.76                 18
    ## # ℹ 1,178 more rows
    ## # ℹ 8 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <int>, homes_powered <dbl>

### Write-up

These data represents three water-wheel vessels that removes trash in
harbors around Baltimore, Maryland. The three vessels are Mr. Trash
Wheel, Professor Trash Wheel, and Gwynnda. In total, there are `1,118`
observations, and some key variables include `name` of the vessel,
`date` of collection, `weight_tons`, `volume_cubic_yards`, litter type
such as `plastic_bottles`, `cigarette_butts`, and `plastic_bags`, and
`homes_powered`. The total weight collected by Professor Trash Wheel is
2283.84 tons. The total number of cigarette butts collected by Gwynnda
in June of 2022 was 18120.

## Problem 3

Clean Zillow datasets

``` r
zipcode_df = 
  read_csv("zillow_data/Zip Codes.csv", na = c("NA", ".", ""), col_names = TRUE) |> 
  janitor::clean_names() |> 
  distinct() ## Gets unique rows
```

    ## Rows: 322 Columns: 7
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (4): County, County Code, File Date, Neighborhood
    ## dbl (3): State FIPS, County FIPS, ZipCode
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
zori_df =
  read_csv("zillow_data/Zip_zori_uc_sfrcondomfr_sm_month_NYC.csv", na = c("NA", ".", ""), col_names = TRUE) |> 
  janitor::clean_names() |> 
  rename(zip_code = region_name) |> 
  pivot_longer(
    cols = x2015_01_31:x2024_08_31,
    names_to = "date_recorded",
    values_to = "zori",
    names_prefix = "x" 
  ) |> 
  mutate(date_recorded = str_replace_all(date_recorded, "_", "-")) |> 
  separate(
    date_recorded, into = c("year", "month", "day"), sep = "-") |> 
  distinct() ## Gets unique rows
```

    ## Rows: 149 Columns: 125
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr   (6): RegionType, StateName, State, City, Metro, CountyName
    ## dbl (119): RegionID, SizeRank, RegionName, 2015-01-31, 2015-02-28, 2015-03-3...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Merge datasets

``` r
zorimerged_df =
  left_join(zori_df, zipcode_df, by = c("zip_code"), relationship = "many-to-many") |> 
  select(-size_rank, -region_type, -county_name, -state_name, -metro, -state_fips, -file_date) |> 
  relocate(neighborhood, .after = city) |> 
  relocate(zip_code, .after = neighborhood)
```

``` r
zorimerged_df
```

    ## # A tibble: 17,516 × 12
    ##    region_id state city     neighborhood zip_code year  month day    zori county
    ##        <dbl> <chr> <chr>    <chr>           <dbl> <chr> <chr> <chr> <dbl> <chr> 
    ##  1     62080 NY    New York West Queens     11368 2015  01    31       NA Queens
    ##  2     62080 NY    New York West Queens     11368 2015  02    28       NA Queens
    ##  3     62080 NY    New York West Queens     11368 2015  03    31       NA Queens
    ##  4     62080 NY    New York West Queens     11368 2015  04    30       NA Queens
    ##  5     62080 NY    New York West Queens     11368 2015  05    31       NA Queens
    ##  6     62080 NY    New York West Queens     11368 2015  06    30       NA Queens
    ##  7     62080 NY    New York West Queens     11368 2015  07    31       NA Queens
    ##  8     62080 NY    New York West Queens     11368 2015  08    31       NA Queens
    ##  9     62080 NY    New York West Queens     11368 2015  09    30       NA Queens
    ## 10     62080 NY    New York West Queens     11368 2015  10    31       NA Queens
    ## # ℹ 17,506 more rows
    ## # ℹ 2 more variables: county_code <chr>, county_fips <dbl>

Unique zip codes and neighborhoods

``` r
length(unique(zorimerged_df$zip_code[!is.na(zorimerged_df$zip_code)]))
```

    ## [1] 149

``` r
length(unique(zorimerged_df$neighborhood[!is.na(zorimerged_df$neighborhood)]))
```

    ## [1] 42

### Write up

The resulting dataset has `17,516` observations. It describes the Zillow
Observed Rent Index (ZORI) for 149 unique zip codes and 42 unique
neighborhoods. The dataset also includes the `year`, `month`, and `day`
of when the ZORI for each observation was recorded. Other notable
variables are `county` and `county_code`.

``` r
unique_zip <- anti_join(zipcode_df, zori_df, by = "zip_code")

unique_zip
```

    ## # A tibble: 171 × 7
    ##    county state_fips county_code county_fips zip_code file_date neighborhood    
    ##    <chr>       <dbl> <chr>             <dbl>    <dbl> <chr>     <chr>           
    ##  1 Bronx          36 005               36005    10464 7/25/07   Southeast Bronx 
    ##  2 Bronx          36 005               36005    10474 7/25/07   Hunts Point and…
    ##  3 Bronx          36 005               36005    10475 7/25/07   Northeast Bronx 
    ##  4 Bronx          36 005               36005    10499 7/25/07   <NA>            
    ##  5 Bronx          36 005               36005    10550 7/25/07   <NA>            
    ##  6 Bronx          36 005               36005    10704 7/25/07   <NA>            
    ##  7 Bronx          36 005               36005    10705 7/25/07   <NA>            
    ##  8 Bronx          36 005               36005    10803 7/25/07   <NA>            
    ##  9 Kings          36 047               36047    11202 7/25/07   <NA>            
    ## 10 Kings          36 047               36047    11224 7/25/07   Southern Brookl…
    ## # ℹ 161 more rows

There are 171 zip codes that are in the zip code dataset but not in the
Zillow Rental Price dataset. This is due to some zip codes being used
for businesses, P.O. boxes, specific buildings such as the Empire State
Buildings, and other non-residential buildings that Zillow would not
have rental listings for. Additionally, many zip codes are associated
with neighborhoods listed as NA which lie outside of NYC and in NYS.
Thus the Zillow Rental Price dataset that focuses on NYC would not have
these zip codes either.

Rental prices in January 2020 vs January 2021

``` r
drop_df =
  zorimerged_df |> 
  select(state, city, neighborhood, zip_code, year, month, zori, county) |> 
  filter(month == "01", year == "2020" | year == "2021") |> 
  pivot_wider(
    names_from = "year",
    values_from = "zori"
    ) |> 
  rename(before_covid = "2020",
         after_covid = "2021") |> 
  mutate(drop_price = before_covid - after_covid)
```

10 zip codes with largest drop in rental price from January 2020 to
January 2021

``` r
top_10 = drop_df |> 
  filter(!is.na(drop_price)) |> ## excludes na values in drop_price
  filter(!is.na(neighborhood)) |> ## excludes na values in neighborhood
  arrange(desc(drop_price)) |> 
  slice(1:10) |> 
  select(-state,-city)
```

``` r
top_10
```

    ## # A tibble: 10 × 7
    ##    neighborhood        zip_code month county before_covid after_covid drop_price
    ##    <chr>                  <dbl> <chr> <chr>         <dbl>       <dbl>      <dbl>
    ##  1 Lower Manhattan        10007 01    New Y…        6334.       5422.       913.
    ##  2 Lower East Side        10009 01    New Y…        3406.       2692.       714.
    ##  3 Gramercy Park and …    10016 01    New Y…        3731.       3019.       712.
    ##  4 Chelsea and Clinton    10001 01    New Y…        4108.       3398.       710.
    ##  5 Lower East Side        10002 01    New Y…        3645.       2935.       710.
    ##  6 Lower Manhattan        10004 01    New Y…        3150.       2444.       706.
    ##  7 Lower Manhattan        10038 01    New Y…        3573.       2876.       698.
    ##  8 Greenwich Village …    10012 01    New Y…        3629.       2942.       686.
    ##  9 Gramercy Park and …    10010 01    New Y…        3697.       3012.       685.
    ## 10 Lower East Side        10003 01    New Y…        3570.       2897.       673.

### Write up

In January 2020, the average rental price is 2861.9347505 while the
average price in January 2021 is 2484.1643495. This shows a drop from
January 2020 to January 2021. The table above further displays the 10
zip codes with the largest drop in rental price from January 2020 to
January 2021 along with their respective neighborhoods. The largest drop
in rental price is 912.5965909 in the zip code 10007 which is associated
with Lower Manhattan while the smallest drop within this list is
672.5404468 in the zip code 10003 which is associated with the Lower
East side. Most of largest rental price drops from January 2020 to 2021
occured in Lower Manhattan and Lower East Side.
